# 服务器端口号
server:
  port: 9090
# 博客配置暂时不写 TODO
#blog
#  name: Kaigee.top

# 数据库连接信息
spring:
  datasource:
    password: your_password
    username: root
    url: jdbc:mysql://114.132.123.49:3306/Kaige_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**
  # Redis
  data:
    redis:
      host: 114.132.123.49
      password:
      port: 6379
      connect-timeout: 100000ms
      database: 1
# jimmer
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation:
    catalog: Kaige_blog
    mode: ERROR

token:
  expireTime: 259200000
  secretKey: "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"



