# 服务器端口号
server:
  port: 9090
# 博客配置暂时不写 TODO
#blog
#  name: Kaigee.top

# 数据库连接信息
spring:
  datasource:
    username: kaige
    password: your_password
    url: jdbc:mysql://114.132.123.49:3306/kaige_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
#      additional-exclude: static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  # Redis
  data:
    redis:
      host: 114.132.123.49
      password: your_password
      port: 6379
      connect-timeout: 100000ms
      database: 1
# jimmer
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation:
    catalog: kaige_blog
    mode: warning

token:
  expireTime: 259200000
  secretKey: "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"

comment:
  notify:
    channel: mail
  default-open: true



